### ISSUE TITLE
Add to cart - WooCommerce Product Add-ons (every option)

### ISSUE THREAD

**Issue by tlygnersjo** [franmastromarino/woo-ajax-add-to-cart#1]
Hi,

I tried your plugin because i saw that it should work with WooCommerce Product Add-ons but when using this it calculates the price and adds all options (even though one should be selected).

I'm using "Multiple Choice" and "Radio buttons" as add-on and it seems to make a sum of all radio button inputs (product price is 10 USD and each option 10 USD and the total amount in checkout is 50 USD (product + 4 options = 50 USD). It should only add the option and price from the selected radio button. Could you fix this? @quadlayers

**Comment by quadlayers** [comment]
Hello @tlygnersjo 

Can you share the link of the page with the issue?

**Comment by tlygnersjo** [comment]
Hello @quadlayers 

Can i send you the link on email or any other non public communication?
