### ISSUE TITLE
Please change feed url

### ISSUE THREAD

**Issue by Tusko** [franmastromarino/woo-ajax-add-to-cart#3]
https://github.com/quadlayers/woo-ajax-add-to-cart/blob/fc52e0720ab91b6d8f4f32f7d4efe570d0e34b65/includes/quadlayers/widget.php#L88

`https://quadlayers.com/news/feed/` -> `https://quadlayers.com/blog/feed/`

**Comment by franmastromarino** [comment]
fixed
